DROP TABLE IF EXISTS  items_comments, bookings, items, users;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
( id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  name varchar(100),
  description VARCHAR(1000),
  available BOOLEAN,
  CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id)
 );

CREATE TABLE IF NOT EXISTS bookings
( id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  item_id BIGINT,
  start_data timestamp,
  end_data timestamp,
  status varchar(50),
  CONSTRAINT fk_bookings_to_users FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id) REFERENCES items(id)
 );

 CREATE TABLE IF NOT EXISTS items_comments
 ( id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   item_id BIGINT,
   user_id BIGINT,
   text varchar(100),
   created timestamp,
   CONSTRAINT fk_comments_to_users FOREIGN KEY(user_id) REFERENCES users(id),
   CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(id)
 );
